within FromModelica;
model Expression
  constant Real a = 1;
  parameter Real b = a * 2;
  parameter Real exp = b ^ b;
  parameter Boolean equal = a == b;
  parameter Boolean diff = a <> b;
  parameter Boolean leq = a <= b;
  parameter Boolean geq = a >= b;
  parameter Boolean lt = a < b;
  parameter Boolean gt = a > b;
  parameter Real ifexp = if b > a then 1 else 0;
  parameter Real elseifexp = if a > b then 0 elseif b == 2 then 1 else -1;
  parameter Integer notexp = if not a < b then 1 else 2;
  parameter Integer andnotexp = if a < b and not a < b then 1 else 2;
  parameter Integer notexppar = if not (a < b) then 1 else 2;
  parameter Integer andnotexppar = if (a < b) and not (a < b) then 1 else 2;
  parameter Real fil[:] = fill(a, 4);
  parameter Real siz1 = size(fil, 1);
  parameter Real siz[:] = size(fil);
  parameter Real arr[:, :, :] = {{{i, j} for i in 1:a} for j in 1:b};
  parameter Real fnabs = abs(-b);
  parameter Real fnsign = sign(b);
  parameter Real fnsqrt = sqrt(b);
  parameter Real fndiv = div(a, b);
  parameter Real fnmod = mod(a, b);
  parameter Real fnrem = rem(a, b);
  parameter Real fnceil = ceil(a / b);
  parameter Real fnfloor = floor(a / b);
  parameter Real fnint = integer(a / b);
  parameter Real fnmax = max(a, b);
  parameter Real fnmaxarr = max(fil);
  parameter Real fnmin = min(a, b);
  parameter Real fnminarr = min(fil);
  parameter Real fnsum = sum(fil);
end Expression;